name: Task01_BrainTumour
target_shape: [256, 256, 128]

base_path: "../datasets/Task01_BrainTumour/"
# consider changing to this, but rn no thank you as it breaks everything hjalte has done,
# so for now i hardcode this in train.py and overwrite it xD oopsie
# Search for keyword: "HARDCODED:" IN ALL files and you will find it.
#base_path: "../datasets/Task01_BrainTumour_test1/fullres/preprocessed/"
#or
#base_path: "../datasets/Task01_BrainTumour/fullres/preprocessed/"
#or
#base_path: "../datasets/Task01_BrainTumour_preprocessed/fullres/"
# just what ever works best for us i guess.
images_subdir: "imagesTr"
labels_subdir: "labelsTr"
num_classes: 4
in_channels: 4
